# Check the examples build on push to main branch or a PR.
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    name: Examples on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest, macos-12, macos-14, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get external dependencies
        if: matrix.os != 'windows-latest'
        run: ./get_extern_deps.sh

      - name: Setup MSYS
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            wget
            git

      - name: Get external dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: ./get_extern_deps.sh
        shell: msys2 {0}

      - name: Build Examples
        run: |
         cd example
         make all

