# Check the examples build on push to main branch or a PR.
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    name: Build Examples
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get external dependencies
        run: ./get_extern_deps.sh
        shell: bash
      - name: Build Examples
        run: |
         cd example
         make all

