# Check the examples build on push to main branch or a PR.
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    name: Examples on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest, macos-12, macos-14]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get external dependencies
        run: ./get_extern_deps.sh

      - name: Build Examples
        run: |
         cd example
         make all

