name: Build Examples

on:
  # Trigger the workflow on push or PR to main.
  # workflow_dispatch allows manual running through the GitHub UI.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    name: HepEVD - Build Examples
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore vendor directory
        id: cache
        uses: actions/cache@v2
        with:
          path: ./web/vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('get_extern_deps.sh') }}
      - name: Get external dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./get_extern_deps.sh -T
      - name: Swap to examples directory
        run: cd examples
      - name: Build Examples
        run: make all

