# Check the examples build on push to main branch or a PR.
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    name: Build Examples
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore vendor directory
        id: cache
        uses: actions/cache@v2
        with:
          path: ./web/vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('get_extern_deps.sh') }}
      - name: Get external dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./get_extern_deps.sh -T
      - name: Build Examples
        run: |
         cd example
         make all

