name: Formatting

on: [push, pull_request, workflow_dispatch]

jobs:
  formatting-check:

    name: HepEVD - clang-format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check clang-format
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '18'
      - name: Check prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          prettier_options: --check



